services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  
  postgres:
    image: postgres:15.0
    ports:
      - 5433:5432 #ホスト側のポート:コンテナ側のポート
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: app #DBに接続する際のユーザー名
      POSTGRES_PASSWORD: password #DBに接続する際のパスワード
      POSTGRES_DB: app #DB名

  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14268:14268"
    environment:
      - LOG_LEVEL=debug

volumes:
  db:
     driver: local